sonar.projectKey=Grad-Tracker_grad-tracker-frontend
sonar.organization=grad-tracker
sonar.host.url=https://sonarcloud.io

sonar.sources=src
sonar.tests=src/__tests__
sonar.test.inclusions=src/**/*.test.ts,src/**/*.test.tsx
sonar.javascript.lcov.reportPaths=coverage/lcov.info

sonar.exclusions=**/node_modules/**,**/.next/**,**/dist/**,**/coverage/**,**/*.d.ts,**/*.config.*,src/components/ui/**
sonar.sourceEncoding=UTF-8
