"use client";

import { useState, useEffect, useMemo } from "react";
import {
  Badge,
  Box,
  Button,
  CloseButton,
  Drawer,
  Flex,
  HStack,
  Icon,
  Input,
  Portal,
  RadioGroup,
  Separator,
  Text,
  VStack,
} from "@chakra-ui/react";
import {
  LuSparkles,
  LuCheck,
  LuRotateCcw,
  LuPackage,
  LuGraduationCap,
  LuBookOpen,
  LuAward,
  LuSearch,
  LuTriangleAlert,
  LuCircleCheck,
  LuCircleX,
} from "react-icons/lu";
import { Switch } from "@/components/ui/switch";
import { Radio } from "@/components/ui/radio";
import { autoGeneratePlan } from "@/lib/planner/auto-generate-orchestrator";
import type { Season, PlanWithMeta } from "@/types/planner";
import { BREADTH_PACKAGES } from "@/types/planner";
import type { AutoGenerateResult } from "@/types/auto-generate";
import { fetchPrograms } from "@/lib/supabase/queries/onboarding";
import type { Program } from "@/types/onboarding";

interface AutoGenerateDialogProps {
  open: boolean;
  onOpenChange: (open: boolean) => void;
  studentId: number;
  programIds: number[];
  plans: PlanWithMeta[];
  activePlanId: number | null;
  onComplete: (planId: number) => void;
}

function getNextSemester(): { season: Season; year: number } {
  const now = new Date();
  const month = now.getMonth();
  if (month < 5) {
    return { season: "Fall", year: now.getFullYear() };
  }
  return { season: "Spring", year: now.getFullYear() + 1 };
}

const TYPE_ORDER: Program["program_type"][] = ["MAJOR", "MINOR", "CERTIFICATE"];

const TYPE_META: Record<
  string,
  { label: string; color: string; icon: typeof LuGraduationCap }
> = {
  MAJOR: { label: "Majors", color: "green", icon: LuGraduationCap },
  MINOR: { label: "Minors", color: "blue", icon: LuBookOpen },
  CERTIFICATE: { label: "Certificates", color: "orange", icon: LuAward },
  GRADUATE: { label: "Graduate", color: "purple", icon: LuGraduationCap },
};

export default function AutoGenerateDialog({
  open,
  onOpenChange,
  studentId,
  programIds,
  plans,
  activePlanId,
  onComplete,
}: AutoGenerateDialogProps) {
  const [mode, setMode] = useState<"new" | "fill">("new");
  const [planName, setPlanName] = useState("");
  const [selectedPlanId, setSelectedPlanId] = useState<number | null>(null);
  const [selectedProgramIds, setSelectedProgramIds] = useState<Set<number>>(
    new Set()
  );
  const [selectedBreadthId, setSelectedBreadthId] = useState<string | null>(
    null
  );
  const [includeSummers, setIncludeSummers] = useState(false);
  const [loading, setLoading] = useState(false);
  const [progress, setProgress] = useState("");
  const [error, setError] = useState<string | null>(null);
  const [result, setResult] = useState<AutoGenerateResult | null>(null);

  // Program data
  const [allPrograms, setAllPrograms] = useState<Program[]>([]);
  const [programsLoading, setProgramsLoading] = useState(false);
  const [programSearch, setProgramSearch] = useState("");

  // Reset state when drawer opens
  useEffect(() => {
    if (!open) return;
    setMode(activePlanId ? "fill" : "new");
    setPlanName("Auto Plan");
    setSelectedPlanId(activePlanId);
    setSelectedProgramIds(new Set(programIds));
    setSelectedBreadthId(null);
    setIncludeSummers(false);
    setLoading(false);
    setProgress("");
    setError(null);
    setResult(null);
    setProgramSearch("");

    if (allPrograms.length === 0) {
      setProgramsLoading(true);
      Promise.all([
        fetchPrograms("MAJOR"),
        fetchPrograms("MINOR"),
        fetchPrograms("CERTIFICATE"),
      ])
        .then(([majors, minors, certs]) => {
          setAllPrograms([...majors, ...minors, ...certs]);
        })
        .finally(() => setProgramsLoading(false));
    }
  }, [open]);

  const filteredByType = useMemo(() => {
    const q = programSearch.toLowerCase().trim();
    const filtered = q
      ? allPrograms.filter((p) => p.name.toLowerCase().includes(q))
      : allPrograms;

    const grouped: Record<string, Program[]> = {
      MAJOR: [],
      MINOR: [],
      CERTIFICATE: [],
    };
    for (const p of filtered) {
      if (grouped[p.program_type]) grouped[p.program_type].push(p);
    }
    return grouped;
  }, [allPrograms, programSearch]);

  function toggleProgram(id: number) {
    setSelectedProgramIds((prev) => {
      const next = new Set(prev);
      if (next.has(id)) next.delete(id);
      else next.add(id);
      return next;
    });
  }

  async function handleGenerate() {
    setLoading(true);
    setError(null);
    setResult(null);

    const { season, year } = getNextSemester();

    try {
      const breadthPackage =
        BREADTH_PACKAGES.find((p) => p.id === selectedBreadthId) ?? null;

      const pIds = Array.from(selectedProgramIds);
      const generatedPlanId =
        mode === "fill" ? (selectedPlanId ?? undefined) : undefined;
      const generatedPlanName =
        mode === "new" ? planName.trim() || "Auto Plan" : undefined;

      const res = await autoGeneratePlan(
        studentId,
        pIds,
        {
          mode,
          planId: generatedPlanId,
          planName: generatedPlanName,
          includeSummers,
          startSeason: season,
          startYear: year,
          breadthPackage,
        },
        setProgress
      );
      setResult(res);
    } catch (err: any) {
      console.error("Auto-generate failed:", err);
      setError(err?.message || "Failed to generate plan. Please try again.");
    } finally {
      setLoading(false);
    }
  }

  function handleDone() {
    if (result) {
      onComplete(result.planId);
    }
    onOpenChange(false);
  }

  const canGenerate =
    !loading &&
    selectedBreadthId != null &&
    selectedProgramIds.size > 0 &&
    (mode === "new" ? planName.trim().length > 0 : selectedPlanId != null);

  return (
    <Drawer.Root
      lazyMount
      open={open}
      onOpenChange={(e) => {
        if (!loading) onOpenChange(e.open);
      }}
      size="md"
      placement="end"
    >
      <Portal>
        <Drawer.Backdrop />
        <Drawer.Positioner>
          <Drawer.Content>
            <Drawer.Header>
              <Drawer.Title
                fontFamily="var(--font-outfit), sans-serif"
                fontWeight="400"
                letterSpacing="-0.02em"
              >
                <HStack gap="2">
                  <LuSparkles size={18} />
                  Auto Generate Plan
                </HStack>
              </Drawer.Title>
              <Drawer.Description color="fg.muted" fontSize="sm">
                Automatically schedule your required courses into semesters.
              </Drawer.Description>
            </Drawer.Header>

            <Drawer.Body>
              {result ? (
                /* ── Success state ── */
                <VStack gap="4" align="stretch">
                  {/* Header box */}
                  {(() => {
                    const { validation } = result;
                    const errors = validation.issues.filter(
                      (i) => i.severity === "error"
                    );
                    const warnings = validation.issues.filter(
                      (i) => i.severity === "warning"
                    );
                    const hasErrors = errors.length > 0;
                    const hasWarnings = warnings.length > 0;

                    return (
                      <>
                        <Box
                          bg={hasErrors ? "orange.subtle" : "green.subtle"}
                          borderRadius="lg"
                          p="4"
                          textAlign="center"
                        >
                          <HStack gap="2" justify="center" mb="2">
                            {hasErrors ? (
                              <LuTriangleAlert size={20} />
                            ) : (
                              <LuCircleCheck size={20} />
                            )}
                            <Text
                              fontWeight="600"
                              color={hasErrors ? "orange.fg" : "green.fg"}
                            >
                              {hasErrors
                                ? "Plan Generated — Some issues found"
                                : "Plan Generated — All requirements verified"}
                            </Text>
                          </HStack>
                          <Text fontSize="sm" color="fg.muted">
                            {result.totalCourses} courses across{" "}
                            {result.semesters.length} semesters (
                            {result.totalCredits} credits)
                          </Text>
                        </Box>

                        {/* Errors */}
                        {hasErrors && (
                          <Box
                            bg="red.subtle"
                            borderRadius="lg"
                            p="3"
                          >
                            <Text
                              fontSize="xs"
                              fontWeight="600"
                              color="red.fg"
                              mb="1.5"
                            >
                              Errors ({errors.length})
                            </Text>
                            <VStack gap="1" align="stretch">
                              {errors.map((issue, i) => (
                                <HStack key={i} gap="1.5" fontSize="xs">
                                  <Icon color="red.fg" boxSize="3.5" flexShrink={0}>
                                    <LuCircleX />
                                  </Icon>
                                  <Text color="fg.muted">{issue.message}</Text>
                                </HStack>
                              ))}
                            </VStack>
                          </Box>
                        )}

                        {/* Warnings */}
                        {hasWarnings && (
                          <Box
                            bg="orange.subtle"
                            borderRadius="lg"
                            p="3"
                          >
                            <Text
                              fontSize="xs"
                              fontWeight="600"
                              color="orange.fg"
                              mb="1.5"
                            >
                              Warnings ({warnings.length})
                            </Text>
                            <VStack gap="1" align="stretch">
                              {warnings.map((issue, i) => (
                                <HStack key={i} gap="1.5" fontSize="xs">
                                  <Icon color="orange.fg" boxSize="3.5" flexShrink={0}>
                                    <LuTriangleAlert />
                                  </Icon>
                                  <Text color="fg.muted">{issue.message}</Text>
                                </HStack>
                              ))}
                            </VStack>
                          </Box>
                        )}

                        {/* Requirement checklist */}
                        {validation.blockStatuses.length > 0 && (
                          <Box>
                            <Text fontSize="xs" fontWeight="600" mb="2" color="fg.muted" textTransform="uppercase" letterSpacing="0.05em">
                              Requirements
                            </Text>
                            <VStack gap="1" align="stretch">
                              {validation.blockStatuses.map((block) => (
                                <HStack key={block.blockId} gap="2" fontSize="xs">
                                  <Icon
                                    color={block.satisfied ? "green.fg" : "red.fg"}
                                    boxSize="3.5"
                                    flexShrink={0}
                                  >
                                    {block.satisfied ? <LuCircleCheck /> : <LuCircleX />}
                                  </Icon>
                                  <Text flex="1" truncate>
                                    {block.blockName}
                                  </Text>
                                  <Text color="fg.muted" flexShrink={0}>
                                    {block.requiredCredits != null
                                      ? `${block.scheduledCredits}/${block.requiredCredits} cr`
                                      : `${block.scheduledCredits} cr`}
                                  </Text>
                                </HStack>
                              ))}
                            </VStack>
                          </Box>
                        )}

                        {/* Gen Ed checklist */}
                        {validation.genEdStatuses.length > 0 && (
                          <Box>
                            <Text fontSize="xs" fontWeight="600" mb="2" color="fg.muted" textTransform="uppercase" letterSpacing="0.05em">
                              General Education
                            </Text>
                            <VStack gap="1" align="stretch">
                              {validation.genEdStatuses.map((ge) => (
                                <HStack key={ge.bucketId} gap="2" fontSize="xs">
                                  <Icon
                                    color={ge.satisfied ? "green.fg" : "red.fg"}
                                    boxSize="3.5"
                                    flexShrink={0}
                                  >
                                    {ge.satisfied ? <LuCircleCheck /> : <LuCircleX />}
                                  </Icon>
                                  <Text flex="1" truncate>
                                    {ge.bucketName}
                                  </Text>
                                  <Text color="fg.muted" flexShrink={0}>
                                    {ge.coveredCredits}/{ge.requiredCredits} cr
                                  </Text>
                                </HStack>
                              ))}
                            </VStack>
                          </Box>
                        )}

                        {/* Unscheduled courses */}
                        {validation.unscheduledCourses.length > 0 && (
                          <Box bg="orange.subtle" borderRadius="lg" p="3">
                            <HStack gap="1.5" mb="1.5">
                              <Icon color="orange.fg" boxSize="3.5">
                                <LuTriangleAlert />
                              </Icon>
                              <Text fontSize="xs" fontWeight="600" color="orange.fg">
                                Unscheduled Courses ({validation.unscheduledCourses.length})
                              </Text>
                            </HStack>
                            <Text fontSize="xs" color="fg.muted">
                              {validation.unscheduledCourses
                                .map((c) => `${c.subject} ${c.number}`)
                                .join(", ")}
                            </Text>
                          </Box>
                        )}
                      </>
                    );
                  })()}

                  <Separator />

                  {/* Semester list */}
                  {result.semesters.map((sem, i) => (
                    <Box key={i} fontSize="sm">
                      <Text fontWeight="600" mb="1">
                        {sem.season} {sem.year}{" "}
                        <Text as="span" color="fg.muted" fontWeight="400">
                          ({sem.totalCredits} cr)
                        </Text>
                      </Text>
                      <Text color="fg.muted" lineClamp={2}>
                        {sem.courses
                          .map((c) => `${c.subject} ${c.number}`)
                          .join(", ")}
                      </Text>
                    </Box>
                  ))}
                </VStack>
              ) : error ? (
                /* ── Error state ── */
                <VStack gap="4" align="stretch">
                  <Box
                    bg="red.subtle"
                    borderRadius="lg"
                    p="4"
                    textAlign="center"
                  >
                    <Text fontWeight="600" color="red.fg" mb="1">
                      Generation Failed
                    </Text>
                    <Text fontSize="sm" color="fg.muted">
                      {error}
                    </Text>
                  </Box>
                </VStack>
              ) : (
                /* ── Config state ── */
                <VStack gap="5" align="stretch">
                  {/* Mode selector */}
                  <Box>
                    <Text fontSize="sm" fontWeight="600" mb="2">
                      Mode
                    </Text>
                    <RadioGroup.Root
                      value={mode}
                      onValueChange={(e) =>
                        setMode(e.value as "new" | "fill")
                      }
                      size="sm"
                    >
                      <VStack gap="2" align="stretch">
                        <Radio value="new">Create new plan</Radio>
                        <Radio value="fill" disabled={plans.length === 0}>
                          Fill existing plan
                        </Radio>
                      </VStack>
                    </RadioGroup.Root>
                  </Box>

                  {/* Mode-specific input */}
                  {mode === "new" ? (
                    <Box>
                      <Text fontSize="sm" fontWeight="600" mb="1.5">
                        Plan Name
                      </Text>
                      <Input
                        value={planName}
                        onChange={(e) => setPlanName(e.target.value)}
                        placeholder="e.g. Auto Plan"
                        size="sm"
                        borderRadius="lg"
                      />
                    </Box>
                  ) : (
                    <Box>
                      <Text fontSize="sm" fontWeight="600" mb="1.5">
                        Select Plan
                      </Text>
                      <VStack gap="1" align="stretch">
                        {plans.map((plan) => (
                          <Button
                            key={plan.id}
                            size="sm"
                            variant={
                              selectedPlanId === plan.id
                                ? "solid"
                                : "outline"
                            }
                            colorPalette={
                              selectedPlanId === plan.id ? "green" : "gray"
                            }
                            borderRadius="lg"
                            justifyContent="flex-start"
                            onClick={() => setSelectedPlanId(plan.id)}
                            fontWeight={
                              selectedPlanId === plan.id ? "600" : "400"
                            }
                          >
                            {plan.name}
                            {plan.course_count > 0 && (
                              <Text
                                as="span"
                                fontSize="xs"
                                color={
                                  selectedPlanId === plan.id
                                    ? "whiteAlpha.800"
                                    : "fg.muted"
                                }
                                ml="auto"
                              >
                                {plan.course_count} courses
                              </Text>
                            )}
                          </Button>
                        ))}
                      </VStack>
                    </Box>
                  )}

                  <Separator />

                  {/* Program selector */}
                  <Box>
                    <Text fontSize="sm" fontWeight="600" mb="1.5">
                      Programs
                    </Text>
                    <Text fontSize="xs" color="fg.muted" mb="3">
                      Select which major, minor, and certificates to include.
                    </Text>

                    <Box position="relative" mb="3">
                      <Box
                        position="absolute"
                        left="3"
                        top="50%"
                        transform="translateY(-50%)"
                        color="fg.muted"
                        zIndex="1"
                      >
                        <LuSearch size={14} />
                      </Box>
                      <Input
                        value={programSearch}
                        onChange={(e) => setProgramSearch(e.target.value)}
                        placeholder="Search programs..."
                        size="sm"
                        borderRadius="lg"
                        pl="9"
                      />
                    </Box>

                    {programsLoading ? (
                      <Text
                        fontSize="sm"
                        color="fg.muted"
                        py="4"
                        textAlign="center"
                      >
                        Loading programs...
                      </Text>
                    ) : (
                      <VStack
                        align="stretch"
                        gap="4"
                        maxH="220px"
                        overflowY="auto"
                        pr="1"
                      >
                        {TYPE_ORDER.map((type) => {
                          const programs = filteredByType[type];
                          if (!programs || programs.length === 0) return null;
                          const meta = TYPE_META[type];

                          return (
                            <Box key={type}>
                              <HStack gap="2" mb="2">
                                <Icon
                                  boxSize="3.5"
                                  color={`${meta.color}.fg`}
                                >
                                  <meta.icon />
                                </Icon>
                                <Text
                                  fontSize="xs"
                                  fontWeight="600"
                                  color="fg.muted"
                                  textTransform="uppercase"
                                  letterSpacing="0.05em"
                                >
                                  {meta.label}
                                </Text>
                                <Badge
                                  size="sm"
                                  variant="subtle"
                                  colorPalette={meta.color}
                                >
                                  {programs.length}
                                </Badge>
                              </HStack>

                              <Flex gap="2" flexWrap="wrap">
                                {programs.map((program) => {
                                  const isSelected =
                                    selectedProgramIds.has(program.id);
                                  return (
                                    <Button
                                      key={program.id}
                                      size="xs"
                                      variant={
                                        isSelected ? "solid" : "outline"
                                      }
                                      colorPalette={
                                        isSelected ? meta.color : "gray"
                                      }
                                      borderRadius="full"
                                      onClick={() =>
                                        toggleProgram(program.id)
                                      }
                                      fontWeight={
                                        isSelected ? "600" : "400"
                                      }
                                    >
                                      {isSelected && (
                                        <LuCheck size={12} />
                                      )}
                                      {program.name}
                                    </Button>
                                  );
                                })}
                              </Flex>
                            </Box>
                          );
                        })}
                      </VStack>
                    )}

                    <Text
                      fontSize="xs"
                      color={
                        selectedProgramIds.size > 0
                          ? "fg.muted"
                          : "orange.fg"
                      }
                      mt="3"
                    >
                      {selectedProgramIds.size > 0
                        ? `${selectedProgramIds.size} program${selectedProgramIds.size !== 1 ? "s" : ""} selected`
                        : "Select at least one program."}
                    </Text>
                  </Box>

                  <Separator />

                  {/* Breadth package selector */}
                  <Box>
                    <HStack gap="1.5" mb="2">
                      <Icon boxSize="3.5" color="fg.muted">
                        <LuPackage />
                      </Icon>
                      <Text fontSize="sm" fontWeight="600">
                        Breadth Package
                      </Text>
                    </HStack>
                    <Text fontSize="xs" color="fg.muted" mb="2">
                      Choose which breadth package to include.
                    </Text>
                    <VStack gap="1" align="stretch">
                      {BREADTH_PACKAGES.map((pkg) => {
                        const isSelected = pkg.id === selectedBreadthId;
                        return (
                          <Box
                            key={pkg.id}
                            as="button"
                            w="full"
                            textAlign="left"
                            px="3"
                            py="2"
                            borderRadius="lg"
                            borderWidth="1px"
                            borderColor={
                              isSelected ? "green.500" : "border.subtle"
                            }
                            bg={isSelected ? "green.subtle" : "bg"}
                            _hover={{
                              bg: isSelected ? "green.subtle" : "bg.subtle",
                              borderColor: isSelected
                                ? "green.500"
                                : "border",
                            }}
                            transition="all 0.15s"
                            cursor="pointer"
                            onClick={() => setSelectedBreadthId(pkg.id)}
                          >
                            <HStack justify="space-between" gap="2">
                              <Box minW="0" flex="1">
                                <Text
                                  fontSize="xs"
                                  fontWeight={isSelected ? "700" : "600"}
                                  color={isSelected ? "green.fg" : "fg"}
                                >
                                  {isSelected && (
                                    <LuCheck
                                      size={12}
                                      style={{
                                        display: "inline",
                                        marginRight: 4,
                                      }}
                                    />
                                  )}
                                  {pkg.name}
                                </Text>
                                <Text
                                  fontSize="2xs"
                                  color="fg.muted"
                                  truncate
                                >
                                  {pkg.description}
                                </Text>
                              </Box>
                              <Text
                                fontSize="2xs"
                                color="fg.subtle"
                                flexShrink={0}
                              >
                                {pkg.totalCreditsRequired} cr
                              </Text>
                            </HStack>
                          </Box>
                        );
                      })}
                    </VStack>
                  </Box>

                  <Separator />

                  {/* Summer toggle */}
                  <HStack justify="space-between">
                    <Box>
                      <Text fontSize="sm" fontWeight="600">
                        Include summers
                      </Text>
                      <Text fontSize="xs" color="fg.muted">
                        Schedule courses in summer semesters too
                      </Text>
                    </Box>
                    <Switch
                      checked={includeSummers}
                      onCheckedChange={(e) => setIncludeSummers(e.checked)}
                      colorPalette="green"
                      size="sm"
                    />
                  </HStack>

                  {/* Progress indicator */}
                  {loading && progress && (
                    <Box
                      bg="bg.subtle"
                      borderRadius="lg"
                      p="3"
                      textAlign="center"
                    >
                      <Text fontSize="sm" color="fg.muted">
                        {progress}
                      </Text>
                    </Box>
                  )}
                </VStack>
              )}
            </Drawer.Body>

            <Drawer.Footer>
              {result ? (
                <Button
                  colorPalette="green"
                  borderRadius="lg"
                  onClick={handleDone}
                >
                  View Plan
                </Button>
              ) : error ? (
                <>
                  <Drawer.ActionTrigger asChild>
                    <Button variant="outline" borderRadius="lg">
                      Cancel
                    </Button>
                  </Drawer.ActionTrigger>
                  <Button
                    colorPalette="green"
                    borderRadius="lg"
                    onClick={() => setError(null)}
                  >
                    <LuRotateCcw size={14} />
                    Try Again
                  </Button>
                </>
              ) : (
                <>
                  <Drawer.ActionTrigger asChild>
                    <Button
                      variant="outline"
                      borderRadius="lg"
                      disabled={loading}
                    >
                      Cancel
                    </Button>
                  </Drawer.ActionTrigger>
                  <Button
                    colorPalette="green"
                    borderRadius="lg"
                    onClick={handleGenerate}
                    disabled={!canGenerate}
                    loading={loading}
                    loadingText="Generating..."
                  >
                    <LuSparkles size={14} />
                    Generate
                  </Button>
                </>
              )}
            </Drawer.Footer>

            {!loading && (
              <Drawer.CloseTrigger asChild>
                <CloseButton size="sm" />
              </Drawer.CloseTrigger>
            )}
          </Drawer.Content>
        </Drawer.Positioner>
      </Portal>
    </Drawer.Root>
  );
}
