"use client";

import { useState, useEffect, useCallback, useMemo, useRef } from "react";
import { useRouter } from "next/navigation";
import {
  Box,
  Button,
  Flex,
  Heading,
  HStack,
  Icon,
  IconButton,
  Text,
} from "@chakra-ui/react";
import PlannerSkeleton, { PlannerPageSkeleton } from "@/components/planner/PlannerSkeleton";
import {
  DndContext,
  DragOverlay,
  PointerSensor,
  KeyboardSensor,
  useSensor,
  useSensors,
  type DragStartEvent,
  type DragEndEvent,
} from "@dnd-kit/core";
import { createClient } from "@/lib/supabase/client";
import { toaster } from "@/components/ui/toaster";
import {
  LuCalendar,
  LuPlus,
  LuArrowLeft,
  LuChevronRight,
} from "react-icons/lu";

import {
  fetchStudentTerms,
  fetchPlannedCourses,
  fetchAvailableCourses,
  fetchCompletedCourseIds,
  fetchPlans,
  createPlan,
  updatePlan,
  deletePlan,
  getOrCreateTerm,
  addTermPlan,
  removeTermPlan,
  addPlannedCourse,
  removePlannedCourse,
  movePlannedCourse,
  fetchGenEdBucketsWithCourses,
  fetchCourseOfferings,
} from "@/lib/supabase/queries/planner";
import { DB_TABLES, PLANNED_COURSE_STATUS } from "@/lib/supabase/queries/schema";
import { logStudentActivity } from "@/lib/supabase/queries/activity";
import { buildAvailabilityMap, isAvailable } from "@/lib/planner/auto-generate";
import { extractPrereqEdges } from "@/lib/planner/prereq-graph";
import {
  arePrereqsSatisfied,
  findBrokenDependents,
  buildCourseTermIndex,
  termSortKey,
} from "@/lib/planner/prereq-validation";

import type {
  Term,
  PlanWithMeta,
  PlannedCourseWithDetails,
  RequirementBlockWithCourses,
  BreadthPackage,
  GraduateTrack,
} from "@/types/planner";
import {
  deduplicateBlocks,
  getGraduateTracks,
  computePerProgramCreditTarget,
  BREADTH_PACKAGES,
} from "@/types/planner";
import type { Course } from "@/types/course";
import type { GenEdBucketWithCourses } from "@/types/auto-generate";

import CoursePanel from "@/components/planner/CoursePanel";
import SemesterGrid from "@/components/planner/SemesterGrid";
import PlannerSummary from "@/components/planner/PlannerSummary";
import AddSemesterDialog from "@/components/planner/AddSemesterDialog";
import RemoveSemesterDialog from "@/components/planner/RemoveSemesterDialog";
import DraggableCourseCard from "@/components/planner/DraggableCourseCard";
import CourseCardGhost from "@/components/planner/CourseCardGhost";
import CreatePlanDialog from "@/components/planner/CreatePlanDialog";
import DeletePlanDialog from "@/components/planner/DeletePlanDialog";
import AutoGenerateDialog from "@/components/planner/AutoGenerateDialog";
import PlansHub from "@/components/planner/PlansHub";
import { EmptyState } from "@/components/ui/empty-state";

const BREADTH_PACKAGE_IDS = new Set(BREADTH_PACKAGES.map((pkg) => pkg.id));

function isValidBreadthPackageId(value: string | null): value is string {
  return !!value && BREADTH_PACKAGE_IDS.has(value);
}


function getCourseActivityLabel(course: Course): string {
  return `${course.subject} ${course.number}`;
}

export interface PlannerViewProps {
  studentId: number;
  mode: "edit" | "readonly";
  initialPlanId?: number;
  /** URL to navigate back to in readonly mode (e.g., /admin/students/5) */
  backHref?: string;
  /** Label for the back breadcrumb in readonly mode (e.g., "Jack Miller") */
  backLabel?: string;
}

export default function PlannerView({
  studentId: propStudentId,
  mode,
  initialPlanId,
  backHref,
  backLabel,
}: PlannerViewProps) {
  const canEdit = mode === "edit";
  const router = useRouter();

  // Auth + student
  const studentId: number = propStudentId;
  const [loading, setLoading] = useState(true);

  // Plan state
  const [plans, setPlans] = useState<PlanWithMeta[]>([]);
  const [activePlanId, setActivePlanId] = useState<number | null>(null);
  const [planDataLoading, setPlanDataLoading] = useState(false);

  // Planner data (scoped to active plan)
  const [terms, setTerms] = useState<Term[]>([]);
  const [plannedCourses, setPlannedCourses] = useState<
    PlannedCourseWithDetails[]
  >([]);
  const [blocks, setBlocks] = useState<RequirementBlockWithCourses[]>([]);
  const [completedIds, setCompletedIds] = useState<Set<number>>(new Set());
  const [genEdBuckets, setGenEdBuckets] = useState<GenEdBucketWithCourses[]>([]);
  const [availabilityMap, setAvailabilityMap] = useState<Map<number, Set<string>>>(
    new Map()
  );
  const [prereqEdges, setPrereqEdges] = useState<Map<number, Set<number>>>(new Map());

  // Breadth package selection (persisted on students row)
  const [selectedBreadthPackageId, setSelectedBreadthPackageId] = useState<
    string | null
  >(null);

  const selectedBreadthPackage: BreadthPackage | null = useMemo(
    () => BREADTH_PACKAGES.find((p) => p.id === selectedBreadthPackageId) ?? null,
    [selectedBreadthPackageId]
  );

  const handleBreadthPackageSelect = useCallback(
    (packageId: string) => {
      if (!studentId || !canEdit) return;
      setSelectedBreadthPackageId(packageId);
      if (activePlanId) {
        localStorage.setItem(
          `gradtracker:breadthPackage:${studentId}:${activePlanId}`,
          packageId
        );
      }
    },
    [studentId, canEdit, activePlanId]
  );

  // Graduate track selection (persisted per plan)
  const [selectedTrackId, setSelectedTrackId] = useState<number | null>(null);

  const handleTrackSelect = useCallback(
    (trackId: number) => {
      setSelectedTrackId(trackId);
      if (studentId && activePlanId && canEdit) {
        localStorage.setItem(
          `gradtracker:track:${studentId}:${activePlanId}`,
          String(trackId)
        );
      }
    },
    [studentId, activePlanId, canEdit]
  );

  // View state: hub (plan cards) or workspace (planner grid)
  const [view, setView] = useState<"hub" | "workspace">("hub");

  // Mobile panel toggle (below lg breakpoint)
  const [mobileTab, setMobileTab] = useState<"courses" | "grid">("grid");

  // UI state
  const [addDialogOpen, setAddDialogOpen] = useState(false);
  const [createPlanDialogOpen, setCreatePlanDialogOpen] = useState(false);
  const [autoGenerateDialogOpen, setAutoGenerateDialogOpen] = useState(false);
  const [deletePlanDialog, setDeletePlanDialog] = useState<{
    open: boolean;
    planId: number | null;
  }>({ open: false, planId: null });
  const [removeDialog, setRemoveDialog] = useState<{
    open: boolean;
    termId: number | null;
  }>({ open: false, termId: null });
  const [removingCourseFromDrawer, setRemovingCourseFromDrawer] = useState(false);
  const [activeDrag, setActiveDrag] = useState<{
    course: Course;
    fromTermId?: number;
  } | null>(null);

  // DnD sensors
  const editSensors = useSensors(
    useSensor(PointerSensor, { activationConstraint: { distance: 5 } }),
    useSensor(KeyboardSensor)
  );
  const sensors = canEdit ? editSensors : [];

  // Derived data
  const activePlan = plans.find((p) => p.id === activePlanId) ?? null;
  const isGraduatePlan = activePlan?.has_graduate_program ?? false;
  const plannedCourseIds = useMemo(
    () => new Set(plannedCourses.map((pc) => pc.course_id)),
    [plannedCourses]
  );
  const courseTermIndex = useMemo(
    () => buildCourseTermIndex(plannedCourses, terms),
    [plannedCourses, terms]
  );
  const courseById = useMemo(() => {
    const map = new Map<number, Course>();
    for (const b of blocks) {
      for (const c of b.courses) map.set(c.id, c);
    }
    for (const bucket of genEdBuckets) {
      for (const c of bucket.courses ?? []) map.set(c.id, c as Course);
    }
    for (const pc of plannedCourses) {
      if (pc.course) map.set(pc.course.id, pc.course);
    }
    return map;
  }, [blocks, genEdBuckets, plannedCourses]);
  const graduateTracks: GraduateTrack[] = useMemo(
    () => (isGraduatePlan ? getGraduateTracks(blocks) : []),
    [blocks, isGraduatePlan]
  );

  const plannerPoolBlocks = useMemo(() => {
    if (isGraduatePlan) return blocks;

    const genEdCourses = (() => {
      const seenCourseIds = new Set<number>();
      return genEdBuckets
        .flatMap((bucket) => bucket.courses ?? [])
        .filter((course) => {
          if (seenCourseIds.has(course.id)) return false;
          seenCourseIds.add(course.id);
          return true;
        });
    })();

    if (!genEdCourses.length) return blocks;

    const hasGeneralEdBlock = blocks.some((block) => {
      const name = block.name.toLowerCase();
      return name.includes("general education") || name.includes("gen ed");
    });

    if (hasGeneralEdBlock) return blocks;

    return [
      ...blocks,
      {
        id: -2,
        program_id: 0,
        name: "General Education",
        rule: "CREDITS_OF",
        n_required: null,
        credits_required: genEdBuckets.reduce(
          (sum, bucket) => sum + Number(bucket.credits_required ?? 0),
          0
        ),
        courses: genEdCourses,
      },
    ];
  }, [blocks, genEdBuckets, isGraduatePlan]);

  // Auto-select first concentration track when a graduate plan loads
  useEffect(() => {
    if (isGraduatePlan && graduateTracks.length >= 2 && selectedTrackId === null) {
      handleTrackSelect(graduateTracks[0].blockId);
    }
  }, [isGraduatePlan, graduateTracks, selectedTrackId, handleTrackSelect]);

  const allDedupedBlocks = useMemo(
    () => deduplicateBlocks(plannerPoolBlocks, { isGraduate: isGraduatePlan }),
    [plannerPoolBlocks, isGraduatePlan]
  );

  const displayBlocks = useMemo(
    () =>
      deduplicateBlocks(plannerPoolBlocks, {
        selectedPackage: isGraduatePlan ? null : selectedBreadthPackage,
        isGraduate: isGraduatePlan,
        selectedTrackId: isGraduatePlan ? selectedTrackId : null,
      }),
    [plannerPoolBlocks, selectedBreadthPackage, isGraduatePlan, selectedTrackId]
  );

  const degreeCreditTarget = useMemo(() => {
    if (displayBlocks.length === 0) return undefined;
    return computePerProgramCreditTarget(displayBlocks, {
      selectedPackage: isGraduatePlan ? null : selectedBreadthPackage,
      isGraduate: isGraduatePlan,
      selectedTrackId: isGraduatePlan ? selectedTrackId : null,
      minimumUndergradCredits: isGraduatePlan ? 0 : 120,
      useLegacyElectivePoolForTotal: !isGraduatePlan,
    });
  }, [displayBlocks, isGraduatePlan, selectedBreadthPackage, selectedTrackId]);

  // ── Load plan-specific data ────────────────────────────
  const loadAbortRef = useRef<AbortController | null>(null);

  const loadPlanData = useCallback(
    async (sid: number, planId: number, graduate = false) => {
      // Cancel any in-flight load
      loadAbortRef.current?.abort();
      const controller = new AbortController();
      loadAbortRef.current = controller;
      const { signal } = controller;

      setPlanDataLoading(true);
      try {
        if (graduate) {
          setSelectedBreadthPackageId(null);
          const savedTrack = localStorage.getItem(
            `gradtracker:track:${sid}:${planId}`
          );
          setSelectedTrackId(savedTrack ? Number(savedTrack) : null);
        } else {
          setSelectedTrackId(null);
        }

        const [termsData, coursesData, blocksData, completedData, genEdData] =
          await Promise.all([
            fetchStudentTerms(sid, planId),
            fetchPlannedCourses(sid, planId),
            fetchAvailableCourses(sid, planId),
            fetchCompletedCourseIds(sid),
            fetchGenEdBucketsWithCourses(),
          ]);

        if (signal.aborted) return;

        // Course IDs present in this plan's universe — drives the prereq
        // graph and availability lookups used by drag-and-drop validation.
        const allCourseIds = Array.from(
          new Set<number>([
            ...blocksData.flatMap((b) => b.courses.map((c) => c.id)),
            ...genEdData.flatMap((bucket) => (bucket.courses ?? []).map((c) => c.id)),
            ...coursesData.map((pc) => pc.course_id),
          ])
        );

        const [offerings, edges] = await Promise.all([
          fetchCourseOfferings(allCourseIds),
          extractPrereqEdges(allCourseIds),
        ]);

        if (signal.aborted) return;

        setTerms(termsData);
        setPlannedCourses(coursesData);
        setBlocks(blocksData);
        setCompletedIds(completedData);
        setGenEdBuckets(genEdData);
        setAvailabilityMap(buildAvailabilityMap(offerings));
        setPrereqEdges(edges);
        if (!graduate) {
          const savedPkg = localStorage.getItem(
            `gradtracker:breadthPackage:${sid}:${planId}`
          );
          setSelectedBreadthPackageId(
            savedPkg && isValidBreadthPackageId(savedPkg) ? savedPkg : null
          );
        }
      } catch (err) {
        if (signal.aborted) return;
        console.error("Failed to load plan data:", err);
        toaster.create({
          title: "Failed to load plan",
          description: "Please try again.",
          type: "error",
        });
        // Ensure we don't keep stale data around on failure
        setTerms([]);
        setPlannedCourses([]);
        setBlocks([]);
        setCompletedIds(new Set());
        setGenEdBuckets([]);
        setAvailabilityMap(new Map());
        setPrereqEdges(new Map());
      } finally {
        if (!signal.aborted) {
          setPlanDataLoading(false);
        }
      }
    },
    []
  );

  // ── Initial load ───────────────────────────────────────
  useEffect(() => {
    let alive = true;

    async function init() {
      setLoading(true);

      try {
        const supabase = createClient();

        // Fetch plans (can fail — must be caught to avoid unhandled rejection)
        const initialPlans = await fetchPlans(studentId);

        let plansData: PlanWithMeta[] = initialPlans;

        // Auto-create default plan if none exist (edit mode only — advisors
        // viewing a student in readonly mode must never write to the DB).
        if (plansData.length === 0 && canEdit) {
          const { data: studentPrograms, error: spErr } = await supabase
            .from(DB_TABLES.studentPrograms)
            .select("program_id")
            .eq("student_id", studentId);

          if (spErr) {
            toaster.create({
              title: "Failed to load programs",
              description: "Please try again.",
              type: "error",
            });
            if (alive) setPlans([]);
            return;
          }

          const programIds = (studentPrograms ?? []).map(
            (sp: any) => sp.program_id
          );

          // createPlan can fail too — allow outer catch to handle
          await createPlan(studentId, "My Plan", null, programIds);
          plansData = await fetchPlans(studentId);
        }

        if (!alive) return;

        setPlans(plansData);

        // If initialPlanId is provided, prefer it on first mount when picking
        // the active plan and open the workspace directly.
        const targetPlan =
          (initialPlanId && plansData.find((p) => p.id === initialPlanId)) ||
          null;
        if (targetPlan) {
          setActivePlanId(targetPlan.id);
          setView("workspace");
          await loadPlanData(
            studentId,
            targetPlan.id,
            targetPlan.has_graduate_program ?? false
          );
        }
      } catch (err) {
        console.error("Planner init failed:", err);
        toaster.create({
          title: "Failed to load planner",
          description: "Please try again.",
          type: "error",
        });
        if (alive) setPlans([]);
      } finally {
        if (alive) setLoading(false);
      }
    }

    init();

    return () => {
      alive = false;
      loadAbortRef.current?.abort();
    };
  }, [studentId, initialPlanId, loadPlanData]);

  // ── Open plan from hub ──────────────────────────────────
  const handleOpenPlan = useCallback(
    async (planId: number) => {
      if (!studentId) return;
      setActivePlanId(planId);
      setView("workspace");
      const plan = plans.find((p) => p.id === planId);
      await loadPlanData(studentId, planId, plan?.has_graduate_program ?? false);
    },
    [studentId, plans, loadPlanData]
  );

  // ── Switch plan (within workspace) ────────────────────
  const handleSwitchPlan = useCallback(
    async (planId: number) => {
      if (planId === activePlanId || !studentId) return;
      setActivePlanId(planId);
      const plan = plans.find((p) => p.id === planId);
      await loadPlanData(studentId, planId, plan?.has_graduate_program ?? false);
    },
    [activePlanId, studentId, plans, loadPlanData]
  );

  // ── Back to hub ───────────────────────────────────────
  const handleBackToHub = useCallback(() => {
    if (!canEdit && backHref) {
      router.push(backHref);
      return;
    }
    setView("hub");
  }, [canEdit, backHref, router]);

  // ── Create plan ────────────────────────────────────────
  const handleCreatePlan = useCallback(
    async (name: string, description: string | null, programIds: number[], autoGenerate = false) => {
      if (!studentId) return;
      try {
        const newPlan = await createPlan(studentId, name, description, programIds);
        const refreshedPlans = await fetchPlans(studentId);
        setPlans(refreshedPlans);
        setActivePlanId(newPlan.id);
        setView("workspace");
        const created = refreshedPlans.find((p) => p.id === newPlan.id);
        await loadPlanData(studentId, newPlan.id, created?.has_graduate_program ?? false);
        toaster.create({ title: `"${name}" created`, type: "success" });
        if (autoGenerate) {
          setAutoGenerateDialogOpen(true);
        }
      } catch (err) {
        console.error("Create plan failed:", err);
        toaster.create({
          title: "Failed to create plan",
          description: "Please try again.",
          type: "error",
        });
      }
    },
    [studentId, loadPlanData]
  );

  // ── Rename plan ────────────────────────────────────────
  const handleRenamePlan = useCallback(async (planId: number, newName: string) => {
    try {
      const previousPlan = plans.find((p) => p.id === planId);
      await updatePlan(planId, { name: newName });
      setPlans((prev) =>
        prev.map((p) => (p.id === planId ? { ...p, name: newName } : p))
      );
      if (studentId && canEdit) {
        await safeLogActivity(studentId, "plan_updated", `Renamed plan to ${newName}`, {
          plan_id: planId,
          previous_name: previousPlan?.name ?? null,
          new_name: newName,
        });
      }
    } catch (err) {
      console.error("Rename plan failed:", err);
      toaster.create({
        title: "Failed to rename plan",
        description: "Please try again.",
        type: "error",
      });
    }
  }, [plans, studentId]);

  // ── Delete plan ────────────────────────────────────────
  const handleDeletePlanRequest = useCallback((planId: number) => {
    setDeletePlanDialog({ open: true, planId });
  }, []);

  const handleDeletePlanConfirmed = useCallback(async () => {
    const planId = deletePlanDialog.planId;
    if (!planId || !studentId) return;

    try {
      const deletedPlan = plans.find((plan) => plan.id === planId);
      await deletePlan(planId);
      const refreshedPlans = await fetchPlans(studentId);
      setPlans(refreshedPlans);

      if (activePlanId === planId) {
        if (view === "workspace" && refreshedPlans.length > 0) {
          const nextPlan = refreshedPlans[0];
          setActivePlanId(nextPlan.id);
          await loadPlanData(
            studentId,
            nextPlan.id,
            nextPlan.has_graduate_program ?? false
          );
        } else {
          setActivePlanId(null);
          setView("hub");
        }
      }

      if (canEdit) {
        await safeLogActivity(studentId, "plan_deleted", `Deleted plan ${deletedPlan?.name ?? "Untitled Plan"}`, {
          plan_id: planId,
        });
      }
      toaster.create({ title: "Plan deleted", type: "info" });
    } catch (err) {
      console.error("Delete plan failed:", err);
      toaster.create({
        title: "Failed to delete plan",
        description: "Please try again.",
        type: "error",
      });
    }
  }, [deletePlanDialog.planId, studentId, activePlanId, view, loadPlanData, plans]);

  // ── Add semester ────────────────────────────────────────
  const handleAddSemester = useCallback(
    async (season: Term["season"], year: number) => {
      if (!studentId || !activePlanId) return;

      try {
        const term = await getOrCreateTerm(season, year);
        await addTermPlan(studentId, term.id, activePlanId);
        setTerms((prev) => [...prev, term]);
        setPlans((prev) =>
          prev.map((p) =>
            p.id === activePlanId ? { ...p, term_count: p.term_count + 1 } : p
          )
        );
        toaster.create({
          title: `${season} ${year} added`,
          type: "success",
        });
      } catch (err) {
        console.error("Add semester failed:", err);
        toaster.create({
          title: "Failed to add semester",
          description: "Please try again.",
          type: "error",
        });
      }
    },
    [studentId, activePlanId]
  );

  // ── Remove semester ─────────────────────────────────────
  const handleRemoveTermRequest = useCallback(
    (termId: number) => {
      const coursesInTerm = plannedCourses.filter((pc) => pc.term_id === termId);
      if (coursesInTerm.length > 0) {
        setRemoveDialog({ open: true, termId });
      } else {
        handleRemoveTermConfirmed(termId);
      }
    },
    [plannedCourses]
  );

  const handleRemoveTermConfirmed = useCallback(
    async (termId?: number) => {
      const id = termId ?? removeDialog.termId;
      if (!studentId || !id || !activePlanId) return;

      const removedCourseCount = plannedCourses.filter((pc) => pc.term_id === id).length;

      try {
        await removeTermPlan(studentId, id, activePlanId);
        setTerms((prev) => prev.filter((t) => t.id !== id));
        setPlannedCourses((prev) => prev.filter((pc) => pc.term_id !== id));
        setPlans((prev) =>
          prev.map((p) =>
            p.id === activePlanId
              ? {
                  ...p,
                  term_count: Math.max(0, p.term_count - 1),
                  course_count: Math.max(0, p.course_count - removedCourseCount),
                }
              : p
          )
        );
        toaster.create({ title: "Semester removed", type: "info" });
      } catch (err: any) {
        toaster.create({
          title: "Error",
          description: err?.message || "Failed to remove semester",
          type: "error",
        });
      }
    },
    [studentId, activePlanId, removeDialog.termId, plannedCourses]
  );

  const handleRemoveCourseFromTerm = useCallback(
    async (course: Course, termId: number) => {
      if (!studentId || !activePlanId || removingCourseFromDrawer) return;

      setRemovingCourseFromDrawer(true);
      try {
        await removePlannedCourse(
          studentId,
          termId,
          course.id,
          activePlanId
        );
        setPlannedCourses((prev) =>
          prev.filter(
            (pc) => !(pc.course_id === course.id && pc.term_id === termId)
          )
        );
        setPlans((prev) =>
          prev.map((p) =>
            p.id === activePlanId
              ? {
                  ...p,
                  course_count: Math.max(0, p.course_count - 1),
                  total_credits: Math.max(0, p.total_credits - (course.credits ?? 0)),
                }
              : p
          )
        );
        toaster.create({
          title: "Course removed",
          description: `${getCourseActivityLabel(course)} was removed from this semester.`,
          type: "success",
        });
      } catch (err: any) {
        toaster.create({
          title: "Failed to remove course",
          description: err?.message || "Please try again.",
          type: "error",
        });
        throw err;
      } finally {
        setRemovingCourseFromDrawer(false);
      }
    },
    [studentId, activePlanId, removingCourseFromDrawer]
  );

  // ── Drag handlers ───────────────────────────────────────
  function handleDragStart(event: DragStartEvent) {
    const { course, fromTermId } = event.active.data.current as {
      course: Course;
      fromTermId?: number;
    };
    setActiveDrag({ course, fromTermId });
  }

  async function handleDragEnd(event: DragEndEvent) {
    setActiveDrag(null);

    const { active, over } = event;
    if (!over || !studentId || !activePlanId) return;

    const { course, fromTermId } = active.data.current as {
      course: Course;
      fromTermId?: number;
    };

    const overId = String(over.id);

    // Snapshot for rollback
    const prevPlannedCourses = plannedCourses;
    const prevPlans = plans;

    if (overId.startsWith("term-")) {
      const toTermId = over.data.current?.term?.id as number | undefined;
      if (!toTermId) return;
      if (fromTermId === toTermId) return;

      const toTerm = terms.find((t) => t.id === toTermId);
      if (!toTerm) return;
      const targetSortKey = termSortKey(toTerm);

      const labelFor = (id: number) => {
        const c = courseById.get(id);
        return c ? `${c.subject} ${c.number}` : `Course #${id}`;
      };

      if (fromTermId) {
        // MOVE: validate then optimistic update

        // 1) Does this course's own prereqs still hold at the destination?
        const prereqResult = arePrereqsSatisfied(
          course.id,
          targetSortKey,
          prereqEdges,
          courseTermIndex,
          completedIds
        );
        if (!prereqResult.satisfied) {
          toaster.create({
            title: `Can't move ${getCourseActivityLabel(course)} there`,
            description: `Requires: ${prereqResult.missing.map(labelFor).join(", ")}`,
            type: "error",
          });
          return;
        }

        // 2) Would moving this break any dependents that take it later?
        const broken = findBrokenDependents(
          course.id,
          targetSortKey,
          prereqEdges,
          courseTermIndex,
          completedIds
        );
        if (broken.length > 0) {
          toaster.create({
            title: `Can't move ${getCourseActivityLabel(course)} there`,
            description: `Would break prerequisites for: ${broken.map(labelFor).join(", ")}`,
            type: "error",
          });
          return;
        }

        // 3) Soft warning when the course isn't typically offered that term.
        if (!isAvailable(course.id, toTerm.season, toTerm.year, availabilityMap)) {
          toaster.create({
            title: `${getCourseActivityLabel(course)} may not be offered in ${toTerm.season} ${toTerm.year}`,
            description: "Verify with your advisor that this section is being taught.",
            type: "warning",
          });
        }

        setPlannedCourses((prev) =>
          prev.map((pc) =>
            pc.course_id === course.id && pc.term_id === fromTermId
              ? { ...pc, term_id: toTermId }
              : pc
          )
        );

        try {
          await movePlannedCourse(
            studentId,
            course.id,
            fromTermId,
            toTermId,
            activePlanId
          );
        } catch (err: any) {
          setPlannedCourses(prevPlannedCourses);
          toaster.create({
            title: "Failed to move course",
            description: err?.message || "The change was reverted. Please try again.",
            type: "error",
          });
        }
      } else {
        // ADD: validate then optimistic update
        if (plannedCourseIds.has(course.id)) return;

        const prereqResult = arePrereqsSatisfied(
          course.id,
          targetSortKey,
          prereqEdges,
          courseTermIndex,
          completedIds
        );
        if (!prereqResult.satisfied) {
          toaster.create({
            title: `Can't add ${getCourseActivityLabel(course)}`,
            description: `Requires: ${prereqResult.missing.map(labelFor).join(", ")}`,
            type: "error",
          });
          return;
        }

        if (!isAvailable(course.id, toTerm.season, toTerm.year, availabilityMap)) {
          toaster.create({
            title: `${getCourseActivityLabel(course)} may not be offered in ${toTerm.season} ${toTerm.year}`,
            description: "Verify with your advisor that this section is being taught.",
            type: "warning",
          });
        }

        setPlannedCourses((prev) => [
          ...prev,
          {
            student_id: studentId,
            term_id: toTermId,
            course_id: course.id,
            status: PLANNED_COURSE_STATUS.planned,
            plan_id: activePlanId,
            course,
          },
        ]);
        setPlans((prev) =>
          prev.map((p) =>
            p.id === activePlanId
              ? {
                  ...p,
                  course_count: p.course_count + 1,
                  total_credits: p.total_credits + (course.credits ?? 0),
                }
              : p
          )
        );

        try {
          await addPlannedCourse(studentId, toTermId, course.id, activePlanId);
        } catch (err: any) {
          setPlannedCourses(prevPlannedCourses);
          setPlans(prevPlans);
          toaster.create({
            title: "Failed to add course",
            description: err?.message || "The change was reverted. Please try again.",
            type: "error",
          });
        }
      }
      return;
    }

    if (fromTermId && (overId === "course-panel" || !overId.startsWith("term-"))) {
      // REMOVE: optimistic update
      setPlannedCourses((prev) =>
        prev.filter(
          (pc) => !(pc.course_id === course.id && pc.term_id === fromTermId)
        )
      );
      setPlans((prev) =>
        prev.map((p) =>
          p.id === activePlanId
            ? {
                ...p,
                course_count: Math.max(0, p.course_count - 1),
                total_credits: Math.max(0, p.total_credits - (course.credits ?? 0)),
              }
            : p
        )
      );

      try {
        await removePlannedCourse(studentId, fromTermId, course.id, activePlanId);
      } catch (err: any) {
        setPlannedCourses(prevPlannedCourses);
        setPlans(prevPlans);
        toaster.create({
          title: "Failed to remove course",
          description: err?.message || "The change was reverted. Please try again.",
          type: "error",
        });
      }
    }
  }

  // ── Loading state ───────────────────────────────────────
  if (loading) {
    return <PlannerPageSkeleton />;
  }

  // ── Render ──────────────────────────────────────────────
  return (
    <Box
      mx={{ base: "-4", md: "-8" }}
      mt="-6"
      display="flex"
      flexDirection="column"
      h="calc(100vh - 80px)"
      overflow="hidden"
    >
      {!canEdit && (
        <Box
          bg="yellow.subtle"
          color="yellow.fg"
          px="4"
          py="2"
          borderRadius="md"
          mb="2"
        >
          <Text fontSize="sm" fontWeight="500">
            Viewing as advisor — read only.
          </Text>
        </Box>
      )}
      {view === "hub" ? (
        <>
          <PlansHub
            plans={plans}
            onOpenPlan={handleOpenPlan}
            onCreatePlan={() => setCreatePlanDialogOpen(true)}
            onRenamePlan={handleRenamePlan}
            onDeletePlan={handleDeletePlanRequest}
            canEdit={canEdit}
          />
        </>
      ) : (
        <>
          {/* Workspace header */}
          <Box
            as="header"
            position="sticky"
            top="0"
            bg="bg"
            borderBottomWidth="1px"
            borderColor="border.subtle"
            zIndex="sticky"
            className="glass-card"
          >
            <Flex justify="space-between" align="center" px={{ base: "4", md: "6" }} py="3">
              {/* Breadcrumb navigation */}
              <HStack gap="2">
                <IconButton
                  aria-label={backHref ? "Back to student" : "Back to plans"}
                  variant="ghost"
                  size="sm"
                  borderRadius="lg"
                  onClick={handleBackToHub}
                  _hover={{ bg: "bg.subtle" }}
                >
                  <LuArrowLeft />
                </IconButton>
                <HStack gap="1.5" fontSize="sm">
                  <Text
                    color="fg.muted"
                    cursor="pointer"
                    _hover={{ color: "blue.fg" }}
                    onClick={handleBackToHub}
                    fontWeight="500"
                    transition="color 0.15s"
                  >
                    {backLabel ?? "Plans"}
                  </Text>
                  <Icon color="fg.subtle" boxSize="3.5">
                    <LuChevronRight />
                  </Icon>
                  <Heading
                    size="md"
                    fontFamily="var(--font-dm-sans), sans-serif"
                    fontWeight="400"
                    letterSpacing="-0.02em"
                  >
                    {activePlan?.name ?? "Plan"}
                  </Heading>
                </HStack>
              </HStack>

              <HStack gap="2">
                {canEdit && (
                  <Button
                    aria-label="Add a semester to the active plan"
                    size="sm"
                    variant="outline"
                    borderRadius="lg"
                    onClick={() => setAddDialogOpen(true)}
                  >
                    <LuPlus size={16} />
                    Add Semester
                  </Button>
                )}
              </HStack>
            </Flex>
          </Box>

          {/* Plan data loading */}
          {planDataLoading ? (
            <PlannerSkeleton />
          ) : (
            <>
              {/* Mobile tab toggle */}
              <HStack
                display={{ base: "flex", lg: "none" }}
                gap="0"
                bg="bg.subtle"
                borderRadius="lg"
                p="0.5"
                mx="4"
                mt="2"
              >
                <Button
                  size="sm"
                  variant={mobileTab === "courses" ? "solid" : "ghost"}
                  colorPalette={mobileTab === "courses" ? "blue" : "gray"}
                  borderRadius="md"
                  flex="1"
                  onClick={() => setMobileTab("courses")}
                >
                  Courses
                </Button>
                <Button
                  size="sm"
                  variant={mobileTab === "grid" ? "solid" : "ghost"}
                  colorPalette={mobileTab === "grid" ? "blue" : "gray"}
                  borderRadius="md"
                  flex="1"
                  onClick={() => setMobileTab("grid")}
                >
                  Schedule
                </Button>
              </HStack>

              <DndContext sensors={sensors} onDragStart={handleDragStart} onDragEnd={handleDragEnd}>
                <Flex flex="1" overflow="hidden" minH="0" className="animate-fade-up">
                  <Box display={{ base: mobileTab === "courses" ? "block" : "none", lg: "block" }}>
                    <CoursePanel
                      blocks={displayBlocks}
                      allDedupedBlocks={allDedupedBlocks}
                      degreeCreditTarget={degreeCreditTarget}
                      completedCourseIds={completedIds}
                      plannedCourseIds={plannedCourseIds}
                      plannedCourses={plannedCourses}
                      isDragActive={!!activeDrag}
                      selectedBreadthPackageId={selectedBreadthPackageId}
                      onBreadthPackageSelect={handleBreadthPackageSelect}
                      isGraduatePlan={isGraduatePlan}
                      graduateTracks={graduateTracks}
                      selectedTrackId={selectedTrackId}
                      onTrackSelect={handleTrackSelect}
                      genEdBuckets={genEdBuckets}
                      canEdit={canEdit}
                    />
                  </Box>

                  <Box
                    display={{ base: mobileTab === "grid" ? "flex" : "none", lg: "flex" }}
                    flex="1"
                    minH="0"
                  >
                  {terms.length === 0 ? (
                    <Flex
                      flex="1"
                      align="center"
                      justify="center"
                      direction="column"
                      gap="4"
                      p="8"
                      className="animate-fade-up-delay-1"
                    >
                      <Box
                        p="8"
                        borderWidth="2px"
                        borderStyle="dashed"
                        borderColor="border.subtle"
                        borderRadius="2xl"
                        textAlign="center"
                        maxW="420px"
                        bg="bg"
                      >
                        <EmptyState
                          icon={<LuCalendar />}
                          title="No semesters yet"
                          description="Add your first semester to start planning your courses."
                          mb="5"
                        >
                          <Text fontSize="xs" color="fg.muted">
                            Drag courses from the pool on the left into your semesters to build your plan.
                          </Text>
                        </EmptyState>
                        {canEdit && (
                          <Button
                            aria-label="Add the first semester to this plan"
                            colorPalette="blue"
                            borderRadius="lg"
                            size="sm"
                            onClick={() => setAddDialogOpen(true)}
                          >
                            <LuPlus size={16} />
                            Add First Semester
                          </Button>
                        )}
                      </Box>
                    </Flex>
                  ) : (
                    <SemesterGrid
                      terms={terms}
                      plannedCourses={plannedCourses}
                      onRemoveTerm={handleRemoveTermRequest}
                      onRemoveCourse={
                        canEdit
                          ? async (course, termId) => {
                              await handleRemoveCourseFromTerm(course, termId);
                            }
                          : undefined
                      }
                      isRemovingCourse={removingCourseFromDrawer}
                      isGraduatePlan={isGraduatePlan}
                      canEdit={canEdit}
                    />
                  )}
                  </Box>
                </Flex>

                <DragOverlay>
                  {activeDrag ? (
                    <Box w="260px">
                      <CourseCardGhost course={activeDrag.course} />
                    </Box>
                  ) : null}
                </DragOverlay>
              </DndContext>

              <PlannerSummary
                terms={terms}
                plannedCourses={plannedCourses}
                blocks={displayBlocks}
                completedCourseIds={completedIds}
                degreeCreditTarget={degreeCreditTarget}
                isGraduatePlan={isGraduatePlan}
              />
            </>
          )}
        </>
      )}

      {/* Dialogs */}
      {canEdit && (
        <AddSemesterDialog
          open={addDialogOpen}
          onOpenChange={setAddDialogOpen}
          onAdd={handleAddSemester}
          existingTerms={terms}
        />
      )}

      {canEdit && (
        <RemoveSemesterDialog
          open={removeDialog.open}
          onOpenChange={(open) => setRemoveDialog((prev) => ({ ...prev, open }))}
          onConfirm={() => handleRemoveTermConfirmed()}
          term={terms.find((t) => t.id === removeDialog.termId) ?? null}
          courseCount={
            removeDialog.termId
              ? plannedCourses.filter((pc) => pc.term_id === removeDialog.termId).length
              : 0
          }
        />
      )}

      {canEdit && (
        <CreatePlanDialog
          open={createPlanDialogOpen}
          onOpenChange={setCreatePlanDialogOpen}
          onCreatePlan={handleCreatePlan}
          existingPlanCount={plans.length}
        />
      )}

      {canEdit && (
        <DeletePlanDialog
          open={deletePlanDialog.open}
          onOpenChange={(open) => setDeletePlanDialog((prev) => ({ ...prev, open }))}
          onConfirm={handleDeletePlanConfirmed}
          plan={plans.find((p) => p.id === deletePlanDialog.planId) ?? null}
        />
      )}

      {canEdit && studentId && (
        <AutoGenerateDialog
          open={autoGenerateDialogOpen}
          onOpenChange={setAutoGenerateDialogOpen}
          studentId={studentId}
          programIds={
            plans.find((p) => p.id === activePlanId)?.program_ids ?? []
          }
          degreeCreditTarget={degreeCreditTarget}
          plans={plans}
          activePlanId={activePlanId}
          onComplete={async (planId) => {
            const refreshed = await fetchPlans(studentId);
            setPlans(refreshed);
            setActivePlanId(planId);
            setView("workspace");
            await loadPlanData(
              studentId,
              planId,
              refreshed.find((p) => p.id === planId)?.has_graduate_program
            );
          }}
        />
      )}
    </Box>
  );
}

async function safeLogActivity(
  studentId: number,
  activityType: Parameters<typeof logStudentActivity>[1],
  message: string,
  metadata: Record<string, unknown>
) {
  try {
    await logStudentActivity(studentId, activityType, message, metadata);
  } catch (error) {
    console.error("Failed to log student activity:", error);
  }
}
