create table if not exists public.student_activity_log (
  id bigint generated by default as identity primary key,
  student_id bigint not null,
  activity_type text not null,
  message text not null,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),

  constraint student_activity_log_student_id_fkey
    foreign key (student_id)
    references public.students (id)
    on delete cascade,

  constraint student_activity_log_activity_type_check
    check (
      activity_type in (
        'course_added',
        'course_removed',
        'plan_created',
        'plan_updated',
        'plan_deleted',
        'major_changed',
        'onboarding_completed'
      )
    )
);

create index if not exists idx_student_activity_log_student_id
  on public.student_activity_log (student_id);

create index if not exists idx_student_activity_log_student_id_created_at
  on public.student_activity_log (student_id, created_at desc);

create index if not exists idx_student_activity_log_activity_type
  on public.student_activity_log (activity_type);
